# Generated by Django 6.0.3 on 2026-03-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scenario',
            name='hint_type',
            field=models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('qr', 'QR Code'), ('call', 'Phone Call'), ('document', 'Document'), ('salary', 'Pay Slip'), ('form', 'Form'), ('news', 'Fact')], default='sms', max_length=20),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='correct_action',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='volatility',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
